<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config [
    <!ELEMENT config (transformer-factory,xsl-path,stylesheets)>
    
    <!ELEMENT transformer-factory (#PCDATA)>
    
    <!ELEMENT xsl-path (#PCDATA)>
    
    <!ELEMENT stylesheets (stylesheet)*>
    
    <!ELEMENT stylesheet (file,parameter*,info?)>
    <!ATTLIST stylesheet id  ID #REQUIRED
                         for (GeneralizationTransformer|DatamodelMapper|SQLGenerator) #REQUIRED>
    
    <!ELEMENT file (#PCDATA)>
    
    <!ELEMENT parameter (#PCDATA)>
    
    <!ELEMENT info (entry)*>
    
    <!ELEMENT entry (#PCDATA)>
    <!ATTLIST entry key NMTOKEN #REQUIRED>
]>
<config>
    <transformer-factory>net.sf.saxon.TransformerFactoryImpl</transformer-factory>
    <xsl-path>/xml/xsl/</xsl-path>
    <stylesheets>
        <stylesheet id="s1" for="GeneralizationTransformer">
            <file>EER2ER.xsl</file>
            <parameter>generalizationId</parameter>
        </stylesheet>
        <stylesheet id="s2" for="DatamodelMapper">
            <file>ER2Relational.xsl</file>
            <parameter>lastStep</parameter>
            <parameter>genAutoKeys</parameter>
        </stylesheet>
        <stylesheet id="s3" for="SQLGenerator">
            <file>Relational2SQL-1999.xsl</file>
            <parameter>useDelimitedIdentifiers</parameter>
            <info>
                <entry key="vendor">ISO</entry>
                <entry key="version">SQL:1999</entry>
            </info>
        </stylesheet>
        <stylesheet id="s4" for="SQLGenerator">
            <file>Relational2SQL-2003.xsl</file>
            <parameter>useDelimitedIdentifiers</parameter>
            <info>
                <entry key="vendor">ISO</entry>
                <entry key="version">SQL:2003</entry>
            </info>
        </stylesheet>
        <stylesheet id="s5" for="SQLGenerator">
            <file>Relational2MySQL-4,1.xsl</file>
            <parameter>useDelimitedIdentifiers</parameter>
            <info>
                <entry key="vendor">MySQL</entry>
                <entry key="version">4.1</entry>
            </info>
        </stylesheet>
        <stylesheet id="s6" for="SQLGenerator">
            <file>Relational2MySQL-5,0.xsl</file>
            <parameter>useDelimitedIdentifiers</parameter>
            <info>
                <entry key="vendor">MySQL</entry>
                <entry key="version">5.6</entry>
            </info>
        </stylesheet>
        <stylesheet id="s7" for="SQLGenerator">
            <file>Relational2Oracle-9i.xsl</file>
            <parameter>useDelimitedIdentifiers</parameter>
            <info>
                <entry key="vendor">Oracle</entry>
                <entry key="version">12c</entry>
            </info>
        </stylesheet>
        
           <!-- IBM temporaer entfernt
           
        <stylesheet id="s8" for="SQLGenerator">
            <file>Relational2DB2-UDB-LUW-8.xsl</file>
            <parameter>useDelimitedIdentifiers</parameter>
            <info>
                <entry key="vendor">IBM DB2 UDB for LUW</entry>
                <entry key="version">8</entry>
            </info>
        </stylesheet>
        
        -->
        
        <stylesheet id="s9" for="SQLGenerator">
            <file>Relational2SQL-Server-2000.xsl</file>
            <parameter>useDelimitedIdentifiers</parameter>
            <info>
                <entry key="vendor">Microsoft SQL Server</entry>
                <entry key="version">2000</entry>
            </info>
        </stylesheet>
        <stylesheet id="s10" for="SQLGenerator">
            <file>Relational2SQL-Server-2005.xsl</file>
            <parameter>useDelimitedIdentifiers</parameter>
            <info>
                <entry key="vendor">Microsoft SQL Server</entry>
                <entry key="version">2005</entry>
            </info>
        </stylesheet>
    </stylesheets>
</config>
